In [42]:
from sklearn.cluster import DBSCAN
import numpy as np
from sklearn.datasets import make_blobs
from sentence_transformers import SentenceTransformer
from sklearn.metrics.pairwise import pairwise_distances


def custom_distance(x, y):
    return np.dot(x, y)


# Calculate pairwise distances using custom distance metric

MODEL = SentenceTransformer("sentence-transformers/all-MiniLM-L6-v2", cache_folder="./cache")

In [15]:
from trafilatura import fetch_url, extract

def getArticle(url):
	downloaded = fetch_url(url)
	res = extract(downloaded)
	# print(res)
	return res

In [33]:
import pandas as pd
df = pd.read_csv('links.csv')

df['0']

0    https://theconversation.com/what-to-expect-fro...
1    https://www.indiatoday.in/technology/news/stor...
2    https://www.windowscentral.com/software-apps/o...
3    https://readwrite.com/chatgpt-5-release-date-p...
4    https://indianexpress.com/article/technology/a...
5    https://www.hindustantimes.com/business/openai...
6    https://www.pymnts.com/artificial-intelligence...
7    https://www.benzinga.com/news/24/05/38611412/s...
8    https://www.digit.in/news/general/openais-gpt-...
9    https://timesofindia.indiatimes.com/technology...
Name: 0, dtype: object

In [55]:
a1 = MODEL.encode([getArticle(i[i.find('http'):]) for i in df['0'] if getArticle(i[i.find('http'):]) is not None])
a2 = MODEL.encode([getArticle(i[i.find('http'):]) for i in df['4'] if getArticle(i[i.find('http'):]) is not None])
# a2 = MODEL.encode([getArticle()])

In [24]:
getArticle("https://www.aljazeera.com/news/2024/2/1/why-did-a-court-cancel-elon-musks-tesla-salary-package")

In [57]:
# Article similarity
from sklearn.metrics.pairwise import cosine_similarity
from scipy.spatial.distance import cdist
def cosine(u,v):
	u = u.reshape(1, -1)
	v = v.reshape(1, -1)
	return cosine_similarity(u, v)
# Assuming you have a matrix 'data' of shape (n, d)
# data = np.array([[x1, y1, z1], [x2, y2, z2], ...])  # Example data
cosine_similarities = cdist(a2, a2, metric=cosine)
np.set_printoptions(precision=2, suppress=True)
print(cosine_similarities)

[[ 1.    0.52  0.47  0.55  0.59  0.46  0.56 -0.    0.6   0.38]
 [ 0.52  1.    0.45  0.57  0.68  0.48  0.58  0.02  0.67  0.38]
 [ 0.47  0.45  1.    0.46  0.51  0.44  0.52  0.04  0.53  0.4 ]
 [ 0.55  0.57  0.46  1.    0.63  0.65  0.52  0.06  0.71  0.36]
 [ 0.59  0.68  0.51  0.63  1.    0.58  0.62  0.09  0.73  0.38]
 [ 0.46  0.48  0.44  0.65  0.58  1.    0.56  0.08  0.61  0.33]
 [ 0.56  0.58  0.52  0.52  0.62  0.56  1.    0.05  0.58  0.4 ]
 [-0.    0.02  0.04  0.06  0.09  0.08  0.05  1.    0.03  0.01]
 [ 0.6   0.67  0.53  0.71  0.73  0.61  0.58  0.03  1.    0.38]
 [ 0.38  0.38  0.4   0.36  0.38  0.33  0.4   0.01  0.38  1.  ]]


In [75]:
# Topic similarity
q = MODEL.encode(["Congress", "India", "Karnataka", "AI", "Machine Learning", "Politics", "Business"])
cosine_similarity(a2, q)

array([[ 0.23,  0.29,  0.43,  0.08,  0.03,  0.23,  0.03],
       [ 0.12,  0.23,  0.48, -0.04,  0.02,  0.16, -0.03],
       [ 0.21,  0.24,  0.41,  0.12,  0.04,  0.21,  0.13],
       [ 0.15,  0.27,  0.54,  0.02,  0.08,  0.22,  0.03],
       [ 0.2 ,  0.24,  0.46,  0.09,  0.03,  0.18, -0.  ],
       [ 0.11,  0.26,  0.47,  0.07,  0.1 ,  0.21,  0.03],
       [ 0.17,  0.27,  0.53,  0.03,  0.03,  0.21,  0.08],
       [ 0.2 ,  0.12,  0.15,  0.2 ,  0.13,  0.14,  0.25],
       [ 0.24,  0.3 ,  0.47,  0.04,  0.08,  0.24,  0.04],
       [ 0.14,  0.2 ,  0.3 ,  0.05,  0.06,  0.2 ,  0.17]], dtype=float32)

: 

In [40]:
np.linalg.norm(a1-q, axis=1)

array([33.52, 34.16], dtype=float32)

In [111]:
getArticle("https://cointelegraph.com/news/ai-gpt2-chatbot-openai-next-upgrade")

In [65]:

arr = np.load('./data/mydata_t5base.npy')
print(arr.shape)
pairwise_dist = pairwise_distances(arr, metric=custom_distance)
print(pairwise_dist)
print(np.min(pairwise_dist))


(926, 768)
[[0.99999988 0.90980279 0.78680974 ... 0.78664768 0.82710123 0.78046346]
 [0.90980279 1.         0.79508483 ... 0.79676282 0.82347822 0.79473567]
 [0.78680974 0.79508483 1.00000012 ... 0.86558568 0.80354065 0.8064363 ]
 ...
 [0.78664768 0.79676282 0.86558568 ... 1.         0.84059024 0.83400536]
 [0.82710123 0.82347822 0.80354065 ... 0.84059024 1.00000012 0.83640814]
 [0.78046346 0.79473567 0.8064363  ... 0.83400536 0.83640814 1.        ]]
0.7041105031967163


In [ ]:

# # X, _ = make_blobs(n_samples=300, centers=4, cluster_std=0.60, random_state=0)
# # print(type(X))
# # Instantiate DBSCAN clustering object
dbscan = DBSCAN(eps=0.5, min_samples=5)
dbscan.fit(pairwise_dist)

labels = dbscan.labels_

# # Number of clusters in labels, ignoring noise if present.
n_clusters_ = len(set(labels)) - (1 if -1 in labels else 0)
n_noise_ = list(labels).count(-1)
print(labels, n_clusters_, n_noise_)

In [22]:
# Kmeans clustering
from sklearn.cluster import KMeans
kmeans = KMeans(n_clusters=12)

# Fit the model
kmeans.fit(arr)

# Get cluster centers
centers = kmeans.cluster_centers_

# Get cluster labels
labels = kmeans.labels_


In [50]:
# Get the within cluster average distance
pairwise_c1 = pairwise_distances(arr_pca)
print(f"Var:{np.var(pairwise_c1)}, Max:{pairwise_c1.max()}, Min:{pairwise_c1.min()}, Mean:{pairwise_c1.mean()}")

Var:0.031797248870134354, Max:0.9828081130981445, Min:0.0, Mean:0.24264566600322723


In [52]:
# Apply PCA
for i in range(1, 101):
	from sklearn.decomposition import PCA
	pca = PCA(n_components=i)
	arr_pca = pca.fit_transform(arr)
	pairwise_c1 = pairwise_distances(arr_pca)
	print(f"{i}: Var:{np.var(pairwise_c1)}, Max:{pairwise_c1.max()}, Min:{pairwise_c1.min()}, Mean:{pairwise_c1.mean()}")

1: Var:0.03179704025387764, Max:0.9828031659126282, Min:0.0, Mean:0.24264611303806305
2: Var:0.03528384491801262, Max:1.0866495370864868, Min:0.0, Mean:0.355901837348938
3: Var:0.03555958345532417, Max:1.1047700643539429, Min:0.0, Mean:0.4336262047290802
4: Var:0.0326727032661438, Max:1.1415445804595947, Min:0.0, Mean:0.49095210433006287
5: Var:0.032133813947439194, Max:1.1452391147613525, Min:0.0, Mean:0.5390974879264832
6: Var:0.03239470347762108, Max:1.256965160369873, Min:0.0, Mean:0.5776236653327942
7: Var:0.03147415444254875, Max:1.264219880104065, Min:0.0, Mean:0.6102604866027832
8: Var:0.029705900698900223, Max:1.2697745561599731, Min:0.0, Mean:0.6401037573814392
9: Var:0.028641195967793465, Max:1.2706310749053955, Min:0.0, Mean:0.6669219136238098
10: Var:0.027755405753850937, Max:1.277609944343567, Min:0.0, Mean:0.6908923983573914
11: Var:0.027207430452108383, Max:1.2905336618423462, Min:0.0, Mean:0.712178111076355
12: Var:0.02652682550251484, Max:1.3188010454177856, Min:0.0, 

In [ ]:
import requests as req
from bs4 import BeautifulSoup

url = ""
soup = BeautifulSoup(req.get(url), 'html.parser')

ps = soup.find_all('p')


In [3]:
import numpy as np
a = np.load('data/mydata_old.npy')

In [6]:
np.linalg.norm(a, axis=1).max()

1.0000001

In [4]:
import pandas as pd
df = pd.read_json('data/queue.json')
df.to_dict()

{'links': {0: 'https://analyticsindiamag.com/i-dont-care-if-we-burn-50-billion-a-year-were-building-agi-says-sam-altman/',
  1: 'https://www.economist.com/the-world-this-week/2024/04/18/business',
  2: 'https://www.economist.com/the-world-this-week/2024/04/25/this-weeks-cover',
  3: 'https://www.theverge.com/2024/5/5/24149543/jack-dorsey-gone-bluesky-board',
  4: 'https://www.theverge.com/2024/5/5/24149543/jack-dorsey-gone-bluesky-board',
  5: 'https://analyticsindiamag.com/elon-musks-ai-startup-xai-expands-to-japan/',
  6: 'https://techcrunch.com/2024/05/04/this-week-in-ai-generative-ai-and-the-problem-of-compensating-creators/',
  7: 'https://www.economist.com/the-world-this-week/2024/03/07/business',
  8: 'https://www.economist.com/the-world-this-week/2024/02/08/this-weeks-covers',
  9: 'https://analyticsindiamag.com/hcltech-and-aws-partner-to-help-enterprises-explore-gen-ai-use-cases-poc-and-solutions/',
  10: 'https://www.theverge.com/2024/5/5/24147995/apple-siri-ai-research-chatb